Repository OCA/credit-control, pull requests merged in 2019-03, with the labels that each got.

#7 [11.0][MIG] partner_risk_insurance
  partner_risk_insurance/README.rst
  partner_risk_insurance/__init__.py
  partner_risk_insurance/__manifest__.py
  partner_risk_insurance/i18n/ca.po
  partner_risk_insurance/i18n/es.po
  partner_risk_insurance/i18n/es_ES.po
  partner_risk_insurance/i18n/partner_risk_insurance.pot
  partner_risk_insurance/i18n/pt.po
  partner_risk_insurance/i18n/pt_BR.po
  partner_risk_insurance/i18n/sl.po
  partner_risk_insurance/models/__init__.py
  partner_risk_insurance/models/credit_policy.py
  partner_risk_insurance/models/res_partner.py
  partner_risk_insurance/readme/CONTRIBUTORS.rst
  partner_risk_insurance/readme/DESCRIPTION.rst
  partner_risk_insurance/readme/USAGE.rst
  partner_risk_insurance/security/ir.model.access.csv
  partner_risk_insurance/static/description/icon.png
  partner_risk_insurance/tests/__init__.py
  partner_risk_insurance/tests/test_partner_risk_insurance.py
  partner_risk_insurance/views/res_partner_view.xml
Labels: approved, needs review

#13 12.0 mig stock financial risk
  stock_financial_risk/README.rst
  stock_financial_risk/__init__.py
  stock_financial_risk/__manifest__.py
  stock_financial_risk/i18n/ca.po
  stock_financial_risk/i18n/de.po
  stock_financial_risk/i18n/es.po
  stock_financial_risk/i18n/es_AR.po
  stock_financial_risk/i18n/es_MX.po
  stock_financial_risk/i18n/fi.po
  stock_financial_risk/i18n/fr.po
  stock_financial_risk/i18n/gl.po
  stock_financial_risk/i18n/hr.po
  stock_financial_risk/i18n/it.po
  stock_financial_risk/i18n/pt.po
  stock_financial_risk/i18n/pt_BR.po
  stock_financial_risk/i18n/ro.po
  stock_financial_risk/i18n/sl.po
  stock_financial_risk/i18n/tr.po
  stock_financial_risk/i18n/tr_TR.po
  stock_financial_risk/i18n/vi_VN.po
  stock_financial_risk/i18n/zh_CN.po
  stock_financial_risk/models/__init__.py
  stock_financial_risk/models/stock.py
  stock_financial_risk/readme/CONTRIBUTORS.rst
  stock_financial_risk/readme/DESCRIPTION.rst
  stock_financial_risk/readme/USAGE.rst
  stock_financial_risk/static/description/index.html
  stock_financial_risk/tests/__init__.py
  stock_financial_risk/tests/test_stock_financial_risk.py
Labels: approved, ready to merge

#17 [IMP] account_financial_risk: Manage risk in multiple invoice confirmation wizard
  account_financial_risk/__manifest__.py
  account_financial_risk/i18n/es.po
  account_financial_risk/models/account_invoice.py
  account_financial_risk/tests/test_account_financial_risk.py
  account_financial_risk/wizards/__init__.py
  account_financial_risk/wizards/account_invoice_state.py
  account_financial_risk/wizards/account_invoice_state_view.xml
Labels: approved
