Repository OCA/credit-control, pull requests merged in 2020-03, with the labels that each got.

#48 [13.0][MIG] partner_risk_insurance: Migration to 13.0
  .isort.cfg
  partner_risk_insurance/README.rst
  partner_risk_insurance/__init__.py
  partner_risk_insurance/__manifest__.py
  partner_risk_insurance/i18n/ca.po
  partner_risk_insurance/i18n/es.po
  partner_risk_insurance/i18n/es_ES.po
  partner_risk_insurance/i18n/partner_risk_insurance.pot
  partner_risk_insurance/i18n/pt.po
  partner_risk_insurance/i18n/pt_BR.po
  partner_risk_insurance/i18n/sl.po
  partner_risk_insurance/models/__init__.py
  partner_risk_insurance/models/credit_policy.py
  partner_risk_insurance/models/res_partner.py
  partner_risk_insurance/readme/CONTRIBUTORS.rst
  partner_risk_insurance/readme/DESCRIPTION.rst
  partner_risk_insurance/readme/USAGE.rst
  partner_risk_insurance/security/ir.model.access.csv
  partner_risk_insurance/static/description/icon.png
  partner_risk_insurance/static/description/index.html
  partner_risk_insurance/tests/__init__.py
  partner_risk_insurance/tests/test_partner_risk_insurance.py
  partner_risk_insurance/views/res_partner_view.xml
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/partner_risk_insurance/odoo/addons/partner_risk_insurance
  setup/partner_risk_insurance/setup.py
Labels: approved, ready to merge

#59 [12.0][IMP] account_financial_risk: Add allow overrisk invoice validation option.
  account_financial_risk/i18n/account_financial_risk.pot
  account_financial_risk/i18n/es.po
  account_financial_risk/models/account_invoice.py
  account_financial_risk/models/res_company.py
  account_financial_risk/models/res_config.py
  account_financial_risk/views/res_config_view.xml
Labels: approved

#61 [12.0][IMP]account_credit_control: Change order to date DESC for credit.control.run model
  account_credit_control/models/credit_control_run.py
Labels: approved, bot is merging ⏳
