Repository OCA/credit-control, pull requests merged in 2020-06, with the labels that each got.

#65 [12.0][IMP] account_financial_risk sale_financial_risk: Performance. Not store fields. Links to values records. Multi-company. Multi-currency.
  account_financial_risk/README.rst
  account_financial_risk/__manifest__.py
  account_financial_risk/data/account_financial_risk_data.xml
  account_financial_risk/i18n/account_financial_risk.pot
  account_financial_risk/i18n/es.po
  account_financial_risk/migrations/12.0.2.0.0/post-migration.py
  account_financial_risk/models/account_invoice.py
  account_financial_risk/models/res_partner.py
  account_financial_risk/readme/DESCRIPTION.rst
  account_financial_risk/readme/USAGE.rst
  account_financial_risk/static/description/financial_risk_click.png
  account_financial_risk/static/description/index.html
  account_financial_risk/static/src/scss/account_financial_risk_table.scss
  account_financial_risk/tests/test_account_financial_risk.py
  account_financial_risk/views/account_financial_risk_view.xml
  account_financial_risk/views/res_config_view.xml
  account_financial_risk/views/res_partner_view.xml
  account_financial_risk/wizards/partner_risk_exceeded_view.xml
  account_payment_return_financial_risk/__manifest__.py
  account_payment_return_financial_risk/migrations/12.0.2.0.0/post-migration.py
  account_payment_return_financial_risk/models/res_partner.py
  account_payment_return_financial_risk/tests/test_payment_return_risk.py
  account_payment_return_financial_risk/views/res_partner_view.xml
  sale_financial_risk/README.rst
  sale_financial_risk/__init__.py
  sale_financial_risk/__manifest__.py
  sale_financial_risk/hooks.py
  sale_financial_risk/i18n/es.po
  sale_financial_risk/i18n/sale_financial_risk.pot
  sale_financial_risk/migrations/12.0.2.0.0/post-migration.py
  sale_financial_risk/migrations/12.0.2.0.0/pre-migration.py
  sale_financial_risk/models/res_partner.py
  sale_financial_risk/models/sale.py
  sale_financial_risk/readme/DESCRIPTION.rst
  sale_financial_risk/static/description/index.html
  sale_financial_risk/tests/test_partner_sale_risk.py
  sale_financial_risk/views/res_partner_view.xml
  sale_financial_risk/views/sale_financial_risk_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#66 [11.0][IMP] account_financial_risk sale_financial_risk: Performance. Not store fields. Links to values records. Multi-company. Multi-currency.
  account_financial_risk/__manifest__.py
  account_financial_risk/data/account_financial_risk_data.xml
  account_financial_risk/migrations/11.0.2.0.0/post-migration.py
  account_financial_risk/models/account_invoice.py
  account_financial_risk/models/res_partner.py
  account_financial_risk/static/src/less/account_financial_risk_table.less
  account_financial_risk/tests/test_account_financial_risk.py
  account_financial_risk/views/account_financial_risk_view.xml
  account_financial_risk/views/res_config_view.xml
  account_financial_risk/views/res_partner_view.xml
  account_financial_risk/wizards/partner_risk_exceeded_view.xml
  account_payment_return_financial_risk/__manifest__.py
  account_payment_return_financial_risk/migrations/11.0.2.0.0/post-migration.py
  account_payment_return_financial_risk/models/res_partner.py
  account_payment_return_financial_risk/tests/test_payment_return_risk.py
  account_payment_return_financial_risk/views/res_partner_view.xml
  sale_financial_risk/__init__.py
  sale_financial_risk/__manifest__.py
  sale_financial_risk/hooks.py
  sale_financial_risk/migrations/11.0.2.0.0/post-migration.py
  sale_financial_risk/migrations/11.0.2.0.0/pre-migration.py
  sale_financial_risk/models/res_partner.py
  sale_financial_risk/models/sale.py
  sale_financial_risk/tests/test_partner_sale_risk.py
  sale_financial_risk/views/res_partner_view.xml
  sale_financial_risk/views/sale_financial_risk_view.xml
Labels: approved, bot is merging ⏳

#63 [11.0][FIX] *_risk: adapt to multicurrency
  sale_financial_risk/models/sale.py
Labels: approved, bot is merging ⏳, ready to merge

#71 [12.0][FIX] *_financial_risk (minor fixes)
  account_financial_risk/views/account_financial_risk_view.xml
  sale_financial_risk/models/sale.py
Labels: approved, bot is merging ⏳

#72 [FIX] account_credit_control: bs3 to bs4
  account_credit_control/report/report_credit_control_summary.xml
Labels: approved, bot is merging ⏳

#73 [FIX] sale_financial_risk: Compute sudo related field commercial_partner_id
  sale_financial_risk/models/sale.py
Labels: approved, bot is merging ⏳

#75 [12.0][FIX] account_credit_control: update website to current git repository
  account_credit_control/__manifest__.py
Labels: bot is merging ⏳

#76 [FIX] account_credit_control: bs3 to bs4
  account_credit_control/report/report_credit_control_summary.xml
Labels: bot is merging ⏳
