Repository OCA/credit-control, pull requests merged in 2021-12, with the labels that each got.

#161 [14.0][IMP/FIX] account_finacial_risk: add improvements
  account_financial_risk/__manifest__.py
  account_financial_risk/models/account_invoice.py
  account_financial_risk/models/res_partner.py
  account_financial_risk/tests/test_account_financial_risk.py
  sale_financial_risk/tests/test_partner_sale_risk.py
Labels: approved

#162 [15.0][IMP] account_financial_risk: forward port fixes
  account_financial_risk/__manifest__.py
  account_financial_risk/models/account_invoice.py
  account_financial_risk/models/res_partner.py
  account_financial_risk/tests/test_account_financial_risk.py
  sale_financial_risk/tests/test_partner_sale_risk.py
Labels: approved, ready to merge, bot is merging ⏳

#124 [MIG] partner_risk_insurance: Migration to 14.0
  partner_risk_insurance/README.rst
  partner_risk_insurance/__init__.py
  partner_risk_insurance/__manifest__.py
  partner_risk_insurance/i18n/ca.po
  partner_risk_insurance/i18n/es.po
  partner_risk_insurance/i18n/es_ES.po
  partner_risk_insurance/i18n/partner_risk_insurance.pot
  partner_risk_insurance/i18n/pt.po
  partner_risk_insurance/i18n/pt_BR.po
  partner_risk_insurance/i18n/sl.po
  partner_risk_insurance/models/__init__.py
  partner_risk_insurance/models/credit_policy.py
  partner_risk_insurance/models/res_partner.py
  partner_risk_insurance/readme/CONTRIBUTORS.rst
  partner_risk_insurance/readme/DESCRIPTION.rst
  partner_risk_insurance/readme/USAGE.rst
  partner_risk_insurance/security/ir.model.access.csv
  partner_risk_insurance/static/description/icon.png
  partner_risk_insurance/static/description/index.html
  partner_risk_insurance/tests/__init__.py
  partner_risk_insurance/tests/test_partner_risk_insurance.py
  partner_risk_insurance/views/res_partner_view.xml
  setup/partner_risk_insurance/odoo/addons/partner_risk_insurance
  setup/partner_risk_insurance/setup.py
Labels: bot is merging ⏳

#164 [FIX] account_financial_risk: Remove customer_rank condition to show financial risk info
  account_financial_risk/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
