Repository OCA/credit-control, pull requests merged in 2022-09, with the labels that each got.

#199 [13.0][IMP] account_invoice_overdue_reminder: handle mail partner_ids
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, bot is merging ⏳

#213 [13.0][FIX] account_invoice_overdue_reminder: prevent error when no overdue date
  account_invoice_overdue_reminder/models/account_move.py
Labels: approved, bot is merging ⏳

#184 [12.0] fix account_credit_control migration script
  account_credit_control/migrations/12.0.3.0.4/pre-migration.py
Labels: approved, ready to merge, bot is merging ⏳

#212 [13.0][IMP] account_invoice_overdue_reminder: decouple mail validation and vals generation
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, bot is merging ⏳

#215 [14.0][FW]account_invoice_overdue_reminder: prevent error when no overdue date
  account_invoice_overdue_reminder/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#216 [14.0][FW] account_invoice_overdue_reminder: decouple mail validation and mail vals generation
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, bot is merging ⏳

#217 [IMP] account-credit-control
  account_credit_control/models/credit_control_line.py
  account_credit_control/models/credit_control_run.py
Labels: approved, bot is merging ⏳

#218 [13.0][FIX] account_invoice_overdue_reminder: add migration scripts for v12 to v13
  account_invoice_overdue_reminder/migrations/13.0.1.0.0/post-migration.py
  account_invoice_overdue_reminder/migrations/13.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳
