Repository OCA/credit-control, pull requests merged in 2022-03, with the labels that each got.

#152 [13.0][FIX] account_financial_risk: Active model not in context from header buttons
  account_financial_risk/models/account_invoice.py
  account_financial_risk/tests/test_account_financial_risk.py
Labels: approved, ready to merge, bot is merging ⏳

#173 [14.0][FIX] account_financial_risk: Cherry-pick v13 PRs 138 and 152
  account_financial_risk/README.rst
  account_financial_risk/__manifest__.py
  account_financial_risk/i18n/account_financial_risk.pot
  account_financial_risk/i18n/es.po
  account_financial_risk/migrations/14.0.2.1.0/pre-migration.py
  account_financial_risk/models/account_invoice.py
  account_financial_risk/models/res_partner.py
  account_financial_risk/readme/CONFIGURE.rst
  account_financial_risk/readme/DESCRIPTION.rst
  account_financial_risk/security/security.xml
  account_financial_risk/tests/test_account_financial_risk.py
  account_financial_risk/views/res_partner_view.xml
  account_financial_risk/wizards/partner_risk_exceeded_view.xml
  sale_financial_risk/tests/test_partner_sale_risk.py
Labels: bot is merging ⏳

#174 [14.0] FIxes sale_financial_risk: Don't duplicate settings box
  sale_financial_risk/views/res_config_settings.xml
Labels: bot is merging ⏳

#176 [14.0][FIX] account_financial_risk: inherit action_post instead of _post
  account_financial_risk/models/account_invoice.py
  account_financial_risk/tests/test_account_financial_risk.py
Labels: approved, bot is merging ⏳
