Repository OCA/credit-control, pull requests merged in 2022-02, with the labels that each got.

#150 [12.0] Backport account_invoice_overdue_warn and account_invoice_overdue_warn_sale
  account_invoice_overdue_warn/README.rst
  account_invoice_overdue_warn/__init__.py
  account_invoice_overdue_warn/__manifest__.py
  account_invoice_overdue_warn/i18n/account_invoice_overdue_warn.pot
  account_invoice_overdue_warn/i18n/fr.po
  account_invoice_overdue_warn/models/__init__.py
  account_invoice_overdue_warn/models/res_partner.py
  account_invoice_overdue_warn/readme/CONTRIBUTORS.rst
  account_invoice_overdue_warn/readme/DESCRIPTION.rst
  account_invoice_overdue_warn/static/description/icon.png
  account_invoice_overdue_warn/static/description/index.html
  account_invoice_overdue_warn/static/description/partner_overdue_invoice_warn.png
  account_invoice_overdue_warn/tests/__init__.py
  account_invoice_overdue_warn/tests/test_overdue_warn.py
  account_invoice_overdue_warn/views/res_partner.xml
  account_invoice_overdue_warn_sale/README.rst
  account_invoice_overdue_warn_sale/__init__.py
  account_invoice_overdue_warn_sale/__manifest__.py
  account_invoice_overdue_warn_sale/i18n/account_invoice_overdue_warn_sale.pot
  account_invoice_overdue_warn_sale/i18n/fr.po
  account_invoice_overdue_warn_sale/models/__init__.py
  account_invoice_overdue_warn_sale/models/sale_order.py
  account_invoice_overdue_warn_sale/readme/CONTRIBUTORS.rst
  account_invoice_overdue_warn_sale/readme/DESCRIPTION.rst
  account_invoice_overdue_warn_sale/static/description/icon.png
  account_invoice_overdue_warn_sale/static/description/index.html
  account_invoice_overdue_warn_sale/static/description/sale_order_overdue_invoice_warn.png
  account_invoice_overdue_warn_sale/views/sale_order.xml
Labels: approved, bot is merging ⏳

#168 [14.0][FIX] account_invoice_overdue_reminder: bad string
  account_invoice_overdue_reminder/models/res_company.py
Labels: bot is merging ⏳

#165 [13.0][MIG]account_invoice_overdue_reminder
  account_invoice_overdue_reminder/README.rst
  account_invoice_overdue_reminder/__init__.py
  account_invoice_overdue_reminder/__manifest__.py
  account_invoice_overdue_reminder/data/mail_template.xml
  account_invoice_overdue_reminder/data/overdue_reminder_result.xml
  account_invoice_overdue_reminder/i18n/account_invoice_overdue_reminder.pot
  account_invoice_overdue_reminder/i18n/fr.po
  account_invoice_overdue_reminder/i18n/it.po
  account_invoice_overdue_reminder/models/__init__.py
  account_invoice_overdue_reminder/models/account_invoice_overdue_reminder.py
  account_invoice_overdue_reminder/models/account_move.py
  account_invoice_overdue_reminder/models/overdue_reminder_action.py
  account_invoice_overdue_reminder/models/overdue_reminder_result.py
  account_invoice_overdue_reminder/models/res_company.py
  account_invoice_overdue_reminder/models/res_partner.py
  account_invoice_overdue_reminder/readme/CONFIGURATION.rst
  account_invoice_overdue_reminder/readme/CONTRIBUTORS.rst
  account_invoice_overdue_reminder/readme/DESCRIPTION.rst
  account_invoice_overdue_reminder/readme/USAGE.rst
  account_invoice_overdue_reminder/security/ir.model.access.csv
  account_invoice_overdue_reminder/security/ir_rule.xml
  account_invoice_overdue_reminder/static/description/icon.png
  account_invoice_overdue_reminder/static/description/index.html
  account_invoice_overdue_reminder/views/account_invoice_overdue_reminder.xml
  account_invoice_overdue_reminder/views/account_move.xml
  account_invoice_overdue_reminder/views/overdue_reminder_action.xml
  account_invoice_overdue_reminder/views/overdue_reminder_result.xml
  account_invoice_overdue_reminder/views/report.xml
  account_invoice_overdue_reminder/views/report_overdue_reminder.xml
  account_invoice_overdue_reminder/views/res_partner.xml
  account_invoice_overdue_reminder/wizard/__init__.py
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard_view.xml
  account_invoice_overdue_reminder/wizard/res_config_settings.py
  account_invoice_overdue_reminder/wizard/res_config_settings_view.xml
  setup/account_invoice_overdue_reminder/odoo/addons/account_invoice_overdue_reminder
  setup/account_invoice_overdue_reminder/setup.py
Labels: bot is merging ⏳

#77 [10.0] Add module account_invoice_overdue_reminder
  account_invoice_overdue_reminder/__init__.py
  account_invoice_overdue_reminder/__manifest__.py
  account_invoice_overdue_reminder/data/mail_template.xml
  account_invoice_overdue_reminder/data/overdue_reminder_result.xml
  account_invoice_overdue_reminder/i18n/fr.po
  account_invoice_overdue_reminder/migrations/10.0.2.0.1/pre-migration.py
  account_invoice_overdue_reminder/migrations/10.0.2.0.2/pre-migration.py
  account_invoice_overdue_reminder/models/__init__.py
  account_invoice_overdue_reminder/models/account_invoice.py
  account_invoice_overdue_reminder/models/account_invoice_overdue_reminder.py
  account_invoice_overdue_reminder/models/company.py
  account_invoice_overdue_reminder/models/config_settings.py
  account_invoice_overdue_reminder/models/overdue_reminder_action.py
  account_invoice_overdue_reminder/models/overdue_reminder_result.py
  account_invoice_overdue_reminder/models/partner.py
  account_invoice_overdue_reminder/readme/CONFIGURATION.rst
  account_invoice_overdue_reminder/readme/CONTRIBUTORS.rst
  account_invoice_overdue_reminder/readme/DESCRIPTION.rst
  account_invoice_overdue_reminder/readme/USAGE.rst
  account_invoice_overdue_reminder/security/ir.model.access.csv
  account_invoice_overdue_reminder/security/rule.xml
  account_invoice_overdue_reminder/views/account_invoice.xml
  account_invoice_overdue_reminder/views/account_invoice_overdue_reminder.xml
  account_invoice_overdue_reminder/views/config_settings.xml
  account_invoice_overdue_reminder/views/overdue_reminder_action.xml
  account_invoice_overdue_reminder/views/overdue_reminder_result.xml
  account_invoice_overdue_reminder/views/partner.xml
  account_invoice_overdue_reminder/views/report.xml
  account_invoice_overdue_reminder/views/report_overdue_reminder.xml
  account_invoice_overdue_reminder/wizard/__init__.py
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard_view.xml
Labels: stale

#172 [14.0][IMP] partner_risk_insurance: Only display info for commercial partner
  partner_risk_insurance/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#171 [13.0][IMP] partner_risk_insurance: Only display info for commercial partner
  partner_risk_insurance/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
