Repository OCA/credit-control, pull requests merged in 2022-08, with the labels that each got.

#198 [13.0] [IMP] account_invoice_overdue_reminder: multicompany user
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, bot is merging ⏳

#201 [13.0][IMP] account_invoice_overdue_reminder: changes to use cron
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, bot is merging ⏳

#203 [13.0][IMP]account_invoice_overdue_reminder: Set default values
  account_invoice_overdue_reminder/__init__.py
  account_invoice_overdue_reminder/__manifest__.py
  account_invoice_overdue_reminder/hooks.py
Labels: approved, ready to merge, bot is merging ⏳

#210 [14.0][FW]account_invoice_overdue_reminder
  account_invoice_overdue_reminder/__init__.py
  account_invoice_overdue_reminder/__manifest__.py
  account_invoice_overdue_reminder/hooks.py
Labels: bot is merging ⏳
