Repository OCA/credit-control, pull requests merged in 2022-11, with the labels that each got.

#227 [15.0][IMP] account_financial_risk: credit limit last modification date field.
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  account_financial_risk/models/res_partner.py
  account_financial_risk/readme/DESCRIPTION.rst
  account_financial_risk/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#228 [15.0][FIX] account_financial_risk: date_credit_limit view in editin mode
  account_financial_risk/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#230 [15.0][FIX] account_financial_risk: Access error when displaying the partner risk exceeded wizard
  account_financial_risk/wizards/parner_risk_exceeded.py
Labels: approved, bot is merging ⏳

#229 [14.0][FIX] account_invoice_overdue_reminder: No ensure_one in check_warnings
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, bot is merging ⏳

#204 [13.0][IMP] sale_payment_sheet_financial_risk: Reduce each risk field depending…
  sale_payment_sheet_financial_risk/README.rst
  sale_payment_sheet_financial_risk/i18n/es.po
  sale_payment_sheet_financial_risk/i18n/sale_payment_sheet_financial_risk.pot
  sale_payment_sheet_financial_risk/models/res_partner.py
  sale_payment_sheet_financial_risk/readme/DESCRIPTION.rst
  sale_payment_sheet_financial_risk/readme/USAGE.rst
  sale_payment_sheet_financial_risk/static/description/deduct_sale_payment_sheet_set.png
  sale_payment_sheet_financial_risk/static/description/deduct_sale_payment_sheet_unset.png
  sale_payment_sheet_financial_risk/static/description/index.html
  sale_payment_sheet_financial_risk/tests/test_sale_payment_sheet_financial_risk.py
  sale_payment_sheet_financial_risk/views/res_partner_view.xml
Labels: bot is merging ⏳, stale

#234 [15.0][IMP] partner_risk_insurance: Change SavepointCase to TransactionCase
  partner_risk_insurance/tests/test_partner_risk_insurance.py
Labels: bot is merging ⏳

#236 account_invoice_overdue_reminder: fix missing sudo
  .copier-answers.yml
  .pre-commit-config.yaml
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, bot is merging ⏳

#232 [12.0][IMP] copier
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
Labels: approved
