Repository OCA/credit-control, pull requests merged in 2022-06, with the labels that each got.

#167 [13.0][backport] account_invoice_overdue_warn*
  account_invoice_overdue_warn/README.rst
  account_invoice_overdue_warn/__init__.py
  account_invoice_overdue_warn/__manifest__.py
  account_invoice_overdue_warn/i18n/account_invoice_overdue_warn.pot
  account_invoice_overdue_warn/i18n/fr.po
  account_invoice_overdue_warn/models/__init__.py
  account_invoice_overdue_warn/models/res_partner.py
  account_invoice_overdue_warn/readme/CONTRIBUTORS.rst
  account_invoice_overdue_warn/readme/DESCRIPTION.rst
  account_invoice_overdue_warn/static/description/icon.png
  account_invoice_overdue_warn/static/description/index.html
  account_invoice_overdue_warn/static/description/partner_overdue_invoice_warn.png
  account_invoice_overdue_warn/tests/__init__.py
  account_invoice_overdue_warn/tests/test_overdue_warn.py
  account_invoice_overdue_warn/views/res_partner.xml
  account_invoice_overdue_warn_sale/README.rst
  account_invoice_overdue_warn_sale/__init__.py
  account_invoice_overdue_warn_sale/__manifest__.py
  account_invoice_overdue_warn_sale/i18n/account_invoice_overdue_warn_sale.pot
  account_invoice_overdue_warn_sale/i18n/fr.po
  account_invoice_overdue_warn_sale/models/__init__.py
  account_invoice_overdue_warn_sale/models/sale_order.py
  account_invoice_overdue_warn_sale/readme/CONTRIBUTORS.rst
  account_invoice_overdue_warn_sale/readme/DESCRIPTION.rst
  account_invoice_overdue_warn_sale/static/description/icon.png
  account_invoice_overdue_warn_sale/static/description/index.html
  account_invoice_overdue_warn_sale/static/description/sale_order_overdue_invoice_warn.png
  account_invoice_overdue_warn_sale/views/sale_order.xml
  setup/account_invoice_overdue_warn/odoo/addons/account_invoice_overdue_warn
  setup/account_invoice_overdue_warn/setup.py
  setup/account_invoice_overdue_warn_sale/odoo/addons/account_invoice_overdue_warn_sale
  setup/account_invoice_overdue_warn_sale/setup.py
Labels: needs review, bot is merging ⏳, stale

#177 [15.0][MIG] partner_risk_insurance
  partner_risk_insurance/README.rst
  partner_risk_insurance/__init__.py
  partner_risk_insurance/__manifest__.py
  partner_risk_insurance/i18n/ca.po
  partner_risk_insurance/i18n/es.po
  partner_risk_insurance/i18n/es_ES.po
  partner_risk_insurance/i18n/it.po
  partner_risk_insurance/i18n/partner_risk_insurance.pot
  partner_risk_insurance/i18n/pt.po
  partner_risk_insurance/i18n/pt_BR.po
  partner_risk_insurance/i18n/sl.po
  partner_risk_insurance/models/__init__.py
  partner_risk_insurance/models/credit_policy.py
  partner_risk_insurance/models/res_partner.py
  partner_risk_insurance/readme/CONTRIBUTORS.rst
  partner_risk_insurance/readme/DESCRIPTION.rst
  partner_risk_insurance/readme/USAGE.rst
  partner_risk_insurance/security/ir.model.access.csv
  partner_risk_insurance/static/description/icon.png
  partner_risk_insurance/static/description/index.html
  partner_risk_insurance/tests/__init__.py
  partner_risk_insurance/tests/test_partner_risk_insurance.py
  partner_risk_insurance/views/res_partner_view.xml
  setup/partner_risk_insurance/odoo/addons/partner_risk_insurance
  setup/partner_risk_insurance/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#197 [13.0][ADD] sale_payment_sheet_financial_risk: New module
  sale_payment_sheet_financial_risk/README.rst
  sale_payment_sheet_financial_risk/__init__.py
  sale_payment_sheet_financial_risk/__manifest__.py
  sale_payment_sheet_financial_risk/i18n/es.po
  sale_payment_sheet_financial_risk/i18n/sale_payment_sheet_financial_risk.pot
  sale_payment_sheet_financial_risk/models/__init__.py
  sale_payment_sheet_financial_risk/models/res_partner.py
  sale_payment_sheet_financial_risk/readme/CONTRIBUTORS.rst
  sale_payment_sheet_financial_risk/readme/DESCRIPTION.rst
  sale_payment_sheet_financial_risk/readme/USAGE.rst
  sale_payment_sheet_financial_risk/static/description/icon.png
  sale_payment_sheet_financial_risk/static/description/index.html
  sale_payment_sheet_financial_risk/tests/__init__.py
  sale_payment_sheet_financial_risk/tests/test_sale_payment_sheet_financial_risk.py
  sale_payment_sheet_financial_risk/views/res_partner_view.xml
  sale_payment_sheet_financial_risk/views/sale_payment_sheet_financial_risk_view.xml
  setup/sale_payment_sheet_financial_risk/odoo/addons/sale_payment_sheet_financial_risk
  setup/sale_payment_sheet_financial_risk/setup.py
Labels: bot is merging ⏳
