Repository OCA/credit-control, pull requests merged in 2023-07, with the labels that each got.

#290 [15.0][IMP] account_credit_control: Add Payment Reference from invoice to communication table
  account_credit_control/i18n/account_credit_control.pot
  account_credit_control/i18n/es.po
  account_credit_control/models/credit_control_communication.py
  account_credit_control/wizard/mail_compose_message.py
Labels: approved, bot is merging ⏳

#291 [16.0][IMP] account_credit_control: Add Payment Reference from invoice to communication table
  account_credit_control/i18n/account_credit_control.pot
  account_credit_control/i18n/es.po
  account_credit_control/models/credit_control_communication.py
  account_credit_control/wizard/mail_compose_message.py
Labels: approved, bot is merging ⏳

#293 [15.0][OU-ADD] account_invoice_overdue_reminder: Migrate changes of mail template
  account_invoice_overdue_reminder/__manifest__.py
  account_invoice_overdue_reminder/migrations/15.0.1.1.1/noupdate_changes.xml
  account_invoice_overdue_reminder/migrations/15.0.1.1.1/post-migration.py
Labels: approved

#294 [16.0][MIG] sale_financial_risk_info: Migration to version 16.0
  sale_financial_risk_info/README.rst
  sale_financial_risk_info/__init__.py
  sale_financial_risk_info/__manifest__.py
  sale_financial_risk_info/i18n/es.po
  sale_financial_risk_info/i18n/it.po
  sale_financial_risk_info/i18n/sale_financial_risk_info.pot
  sale_financial_risk_info/models/__init__.py
  sale_financial_risk_info/models/res_partner.py
  sale_financial_risk_info/models/sale.py
  sale_financial_risk_info/readme/CONFIGURE.rst
  sale_financial_risk_info/readme/CONTRIBUTORS.rst
  sale_financial_risk_info/readme/DESCRIPTION.rst
  sale_financial_risk_info/readme/USAGE.rst
  sale_financial_risk_info/static/description/icon.png
  sale_financial_risk_info/static/description/index.html
  sale_financial_risk_info/tests/__init__.py
  sale_financial_risk_info/tests/test_sale_financial_risk_info.py
  sale_financial_risk_info/views/res_partner_view.xml
  sale_financial_risk_info/views/sale_order_view.xml
  setup/sale_financial_risk_info/odoo/addons/sale_financial_risk_info
  setup/sale_financial_risk_info/setup.py
Labels: approved, bot is merging ⏳

#295 [IMP] account_financial_risk: problems of partner view are fixed
  account_financial_risk/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#299 [16.0][MIG] stock_financial_risk
  setup/stock_financial_risk/odoo/addons/stock_financial_risk
  setup/stock_financial_risk/setup.py
  stock_financial_risk/README.rst
  stock_financial_risk/__init__.py
  stock_financial_risk/__manifest__.py
  stock_financial_risk/i18n/ca.po
  stock_financial_risk/i18n/de.po
  stock_financial_risk/i18n/es.po
  stock_financial_risk/i18n/es_AR.po
  stock_financial_risk/i18n/es_MX.po
  stock_financial_risk/i18n/fi.po
  stock_financial_risk/i18n/fr.po
  stock_financial_risk/i18n/gl.po
  stock_financial_risk/i18n/hr.po
  stock_financial_risk/i18n/it.po
  stock_financial_risk/i18n/pt.po
  stock_financial_risk/i18n/pt_BR.po
  stock_financial_risk/i18n/ro.po
  stock_financial_risk/i18n/sl.po
  stock_financial_risk/i18n/stock_financial_risk.pot
  stock_financial_risk/i18n/tr.po
  stock_financial_risk/i18n/tr_TR.po
  stock_financial_risk/i18n/vi_VN.po
  stock_financial_risk/i18n/zh_CN.po
  stock_financial_risk/models/__init__.py
  stock_financial_risk/models/stock.py
  stock_financial_risk/readme/CONTRIBUTORS.rst
  stock_financial_risk/readme/DESCRIPTION.rst
  stock_financial_risk/readme/USAGE.rst
  stock_financial_risk/static/description/icon.png
  stock_financial_risk/static/description/index.html
  stock_financial_risk/tests/__init__.py
  stock_financial_risk/tests/test_stock_financial_risk.py
Labels: needs review, migration, bot is merging ⏳
