Repository OCA/credit-control, pull requests merged in 2023-06, with the labels that each got.

#286 [15.0][FIX] xxx_financial_risk: Inconsistent 'compute_sudo' for computed fields
  account_financial_risk/models/res_partner.py
  account_payment_return_financial_risk/models/res_partner.py
  sale_payment_sheet_financial_risk/models/res_partner.py
Labels: approved, bot is merging ⏳

#287 [16.0][FIX] account_credit_control: avoid AccessError in open_credit_lines()
  account_credit_control/models/credit_control_run.py
  account_credit_control/tests/test_credit_control_run.py
Labels: approved, bot is merging ⏳

#257 [12.0][FIX] account_invoice_overdue_reminder: Avoid ensure_one errors
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, bot is merging ⏳, stale

#285 Update __manifest__.py
  account_invoice_overdue_reminder/__manifest__.py
Labels: approved, ready to merge, bot is merging ⏳

#289 [14.0][IMP] account_credit_control: Add Payment Reference from invoice to communication table
  account_credit_control/i18n/account_credit_control.pot
  account_credit_control/i18n/es.po
  account_credit_control/models/credit_control_communication.py
Labels: approved, bot is merging ⏳
