Repository OCA/credit-control, pull requests merged in 2023-12, with the labels that each got.

#283 [14.0][MIG] account_invoice_overdue_reminder: Add credit notes to overdue e-mail
  account_invoice_overdue_reminder/data/mail_template.xml
  account_invoice_overdue_reminder/models/account_invoice_overdue_reminder.py
  account_invoice_overdue_reminder/readme/newsfragments/226.feature.rst
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard_view.xml
Labels: approved, bot is merging ⏳

#345 [15.0][IMP] account_invoice_overdue_reminder: Add credit notes to overdue e-mail (forward port)
  account_invoice_overdue_reminder/README.rst
  account_invoice_overdue_reminder/data/mail_template.xml
  account_invoice_overdue_reminder/models/account_invoice_overdue_reminder.py
  account_invoice_overdue_reminder/readme/newsfragments/226.feature.rst
  account_invoice_overdue_reminder/static/description/index.html
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard_view.xml
Labels: approved, bot is merging ⏳

#334 [FIX][16.0] account_invoice_overdue_reminder: remind partially paid invoices
  account_invoice_overdue_reminder/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#311 [FIX] account_invoice_overdue_reminder : fix html escape
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, bot is merging ⏳

#329 [16.0][IMP] account_invoice_overdue_reminder: hide button if reminded
  account_invoice_overdue_reminder/models/account_move.py
  account_invoice_overdue_reminder/views/account_move.xml
Labels: approved, ready to merge, bot is merging ⏳

#349 [16.0][MIG] account_invoice_overdue_warn
  account_invoice_overdue_warn/README.rst
  account_invoice_overdue_warn/__init__.py
  account_invoice_overdue_warn/__manifest__.py
  account_invoice_overdue_warn/i18n/account_invoice_overdue_warn.pot
  account_invoice_overdue_warn/i18n/ca.po
  account_invoice_overdue_warn/i18n/es.po
  account_invoice_overdue_warn/i18n/fr.po
  account_invoice_overdue_warn/i18n/pt_BR.po
  account_invoice_overdue_warn/models/__init__.py
  account_invoice_overdue_warn/models/res_partner.py
  account_invoice_overdue_warn/readme/CONTRIBUTORS.rst
  account_invoice_overdue_warn/readme/DESCRIPTION.rst
  account_invoice_overdue_warn/static/description/icon.png
  account_invoice_overdue_warn/static/description/index.html
  account_invoice_overdue_warn/static/description/partner_overdue_invoice_warn.png
  account_invoice_overdue_warn/tests/__init__.py
  account_invoice_overdue_warn/tests/test_overdue_warn.py
  account_invoice_overdue_warn/views/res_partner.xml
  setup/account_invoice_overdue_warn/odoo/addons/account_invoice_overdue_warn
  setup/account_invoice_overdue_warn/setup.py
Labels: bot is merging ⏳

#350 [16.0][MIG] account_invoice_overdue_warn_sale
  account_invoice_overdue_warn_sale/README.rst
  account_invoice_overdue_warn_sale/__init__.py
  account_invoice_overdue_warn_sale/__manifest__.py
  account_invoice_overdue_warn_sale/i18n/account_invoice_overdue_warn_sale.pot
  account_invoice_overdue_warn_sale/i18n/ca.po
  account_invoice_overdue_warn_sale/i18n/es.po
  account_invoice_overdue_warn_sale/i18n/fr.po
  account_invoice_overdue_warn_sale/i18n/pt_BR.po
  account_invoice_overdue_warn_sale/models/__init__.py
  account_invoice_overdue_warn_sale/models/sale_order.py
  account_invoice_overdue_warn_sale/readme/CONTRIBUTORS.rst
  account_invoice_overdue_warn_sale/readme/DESCRIPTION.rst
  account_invoice_overdue_warn_sale/static/description/icon.png
  account_invoice_overdue_warn_sale/static/description/index.html
  account_invoice_overdue_warn_sale/static/description/sale_order_overdue_invoice_warn.png
  account_invoice_overdue_warn_sale/views/sale_order.xml
  setup/account_invoice_overdue_warn_sale/odoo/addons/account_invoice_overdue_warn_sale
  setup/account_invoice_overdue_warn_sale/setup.py
Labels: bot is merging ⏳
