Repository OCA/credit-control, pull requests merged in 2023-11, with the labels that each got.

#332 [16.0][FIX] account_invoice_overdue_reminder: TypeError: '>' not supported
  account_invoice_overdue_reminder/models/account_move.py
Labels: approved, bot is merging ⏳

#341 [15.0][FIX] account_financial_risk: Recover original behavior of include checks to be not need to compute risk exception
  account_financial_risk/models/res_partner.py
Labels: approved, bot is merging ⏳

#342 [16.0][FIX] account_financial_risk: Recover original behavior of include checks to be not need to compute risk exception
  account_financial_risk/models/res_partner.py
Labels: bot is merging ⏳

#305 [16.0][MIG] partner_risk_insurance: Migration to 16.0
  partner_risk_insurance/README.rst
  partner_risk_insurance/__init__.py
  partner_risk_insurance/__manifest__.py
  partner_risk_insurance/i18n/ca.po
  partner_risk_insurance/i18n/es.po
  partner_risk_insurance/i18n/es_ES.po
  partner_risk_insurance/i18n/it.po
  partner_risk_insurance/i18n/partner_risk_insurance.pot
  partner_risk_insurance/i18n/pt.po
  partner_risk_insurance/i18n/pt_BR.po
  partner_risk_insurance/i18n/sl.po
  partner_risk_insurance/models/__init__.py
  partner_risk_insurance/models/credit_policy.py
  partner_risk_insurance/models/res_partner.py
  partner_risk_insurance/readme/CONTRIBUTORS.rst
  partner_risk_insurance/readme/DESCRIPTION.rst
  partner_risk_insurance/readme/USAGE.rst
  partner_risk_insurance/security/ir.model.access.csv
  partner_risk_insurance/static/description/icon.png
  partner_risk_insurance/static/description/index.html
  partner_risk_insurance/templates/invoice_risk_insurance_template.xml
  partner_risk_insurance/tests/__init__.py
  partner_risk_insurance/tests/test_partner_risk_insurance.py
  partner_risk_insurance/views/res_partner_view.xml
  partner_risk_insurance/wizard/__init__.py
  partner_risk_insurance/wizard/invoice_risk_insurance_wizard.py
  partner_risk_insurance/wizard/invoice_risk_insurance_wizard.xml
  setup/partner_risk_insurance/odoo/addons/partner_risk_insurance
  setup/partner_risk_insurance/setup.py
Labels: approved, ready to merge, bot is merging ⏳
