Repository OCA/credit-control, pull requests merged in 2024-02, with the labels that each got.

#355 [IMP] [15.0] partner_risk_insurance: Insure invoices with credit policies
  partner_risk_insurance/README.rst
  partner_risk_insurance/__manifest__.py
  partner_risk_insurance/i18n/es.po
  partner_risk_insurance/i18n/partner_risk_insurance.pot
  partner_risk_insurance/models/__init__.py
  partner_risk_insurance/models/account_move.py
  partner_risk_insurance/models/credit_policy_company.py
  partner_risk_insurance/models/credit_policy_state.py
  partner_risk_insurance/models/res_partner.py
  partner_risk_insurance/readme/CONTRIBUTORS.rst
  partner_risk_insurance/readme/USAGE.rst
  partner_risk_insurance/security/ir.model.access.csv
  partner_risk_insurance/static/description/index.html
  partner_risk_insurance/tests/__init__.py
  partner_risk_insurance/tests/test_invoice_credit_policy.py
  partner_risk_insurance/views/account_move_view.xml
  partner_risk_insurance/views/credit_policy_company_view.xml
  partner_risk_insurance/views/res_partner_view.xml
  partner_risk_insurance/wizard/invoice_risk_insurance_wizard.xml
Labels: needs review, bot is merging ⏳

#359 [15.0][IMP] partner_risk_insurance: Performance installation on large databases
  partner_risk_insurance/README.rst
  partner_risk_insurance/__init__.py
  partner_risk_insurance/__manifest__.py
  partner_risk_insurance/hooks.py
  partner_risk_insurance/migrations/15.0.3.0.1/pre-migration.py
  partner_risk_insurance/static/description/index.html
Labels: approved, bot is merging ⏳

#319 [FIX] sale_financial_risk: When evaluating risk, convert the amount to correct currency
  sale_financial_risk/models/sale.py
  sale_financial_risk/tests/test_partner_sale_risk.py
Labels: needs review, approved, bot is merging ⏳

#360 [16.0] [FWP] partner_risk_insurance: PR 355, PR 359
  partner_risk_insurance/README.rst
  partner_risk_insurance/__init__.py
  partner_risk_insurance/__manifest__.py
  partner_risk_insurance/hooks.py
  partner_risk_insurance/i18n/es.po
  partner_risk_insurance/i18n/partner_risk_insurance.pot
  partner_risk_insurance/migrations/16.0.3.0.1/pre-migration.py
  partner_risk_insurance/models/__init__.py
  partner_risk_insurance/models/account_move.py
  partner_risk_insurance/models/credit_policy_company.py
  partner_risk_insurance/models/credit_policy_state.py
  partner_risk_insurance/models/res_partner.py
  partner_risk_insurance/readme/CONTRIBUTORS.rst
  partner_risk_insurance/readme/USAGE.rst
  partner_risk_insurance/security/ir.model.access.csv
  partner_risk_insurance/static/description/index.html
  partner_risk_insurance/tests/__init__.py
  partner_risk_insurance/tests/test_invoice_credit_policy.py
  partner_risk_insurance/views/account_move_view.xml
  partner_risk_insurance/views/credit_policy_company_view.xml
  partner_risk_insurance/views/res_partner_view.xml
  partner_risk_insurance/wizard/invoice_risk_insurance_wizard.xml
Labels: needs review, bot is merging ⏳

#361 [15.0][FIX] sale_financial_risk: When evaluating risk, convert the amount to correct currency Forward port of #319
  sale_financial_risk/models/sale.py
  sale_financial_risk/tests/test_partner_sale_risk.py
Labels: needs review, approved, bot is merging ⏳

#364 [15.0][FIX] sale_financial_risk: fix test
  sale_financial_risk/tests/test_partner_sale_risk.py
Labels: approved, bot is merging ⏳

#362 [IMP] partner_risk_insurance: improve UX
  account_credit_control/models/res_partner.py
  partner_risk_insurance/README.rst
  partner_risk_insurance/__manifest__.py
  partner_risk_insurance/i18n/es.po
  partner_risk_insurance/i18n/es_ES.po
  partner_risk_insurance/i18n/partner_risk_insurance.pot
  partner_risk_insurance/models/res_partner.py
  partner_risk_insurance/readme/CONTRIBUTORS.rst
  partner_risk_insurance/security/ir.model.access.csv
  partner_risk_insurance/static/description/index.html
  partner_risk_insurance/tests/test_partner_risk_insurance.py
  partner_risk_insurance/views/res_partner_view.xml
Labels: needs review, approved, bot is merging ⏳
