Repository OCA/credit-control, pull requests merged in 2025-03, with the labels that each got.

#427 [18.0][MIG] account_invoice_overdue_warn
  account_invoice_overdue_warn/README.rst
  account_invoice_overdue_warn/__init__.py
  account_invoice_overdue_warn/__manifest__.py
  account_invoice_overdue_warn/i18n/account_invoice_overdue_warn.pot
  account_invoice_overdue_warn/i18n/ca.po
  account_invoice_overdue_warn/i18n/es.po
  account_invoice_overdue_warn/i18n/fr.po
  account_invoice_overdue_warn/i18n/it.po
  account_invoice_overdue_warn/i18n/pt_BR.po
  account_invoice_overdue_warn/models/__init__.py
  account_invoice_overdue_warn/models/res_partner.py
  account_invoice_overdue_warn/pyproject.toml
  account_invoice_overdue_warn/readme/CONTRIBUTORS.md
  account_invoice_overdue_warn/readme/DESCRIPTION.md
  account_invoice_overdue_warn/static/description/icon.png
  account_invoice_overdue_warn/static/description/index.html
  account_invoice_overdue_warn/static/description/partner_overdue_invoice_warn.png
  account_invoice_overdue_warn/tests/__init__.py
  account_invoice_overdue_warn/tests/test_overdue_warn.py
  account_invoice_overdue_warn/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#419 [16.0][FIX] account_invoice_overdue_reminder: access error
  account_invoice_overdue_reminder/views/account_move.xml
Labels: bot is merging ⏳

#438 [17.0][IMP+FIX] account_credit_control: Defining the right data in the communication email
  account_credit_control/models/credit_control_communication.py
  account_credit_control/report/report_credit_control_summary.xml
  account_credit_control/views/credit_control_line.xml
Labels: approved, bot is merging ⏳

#441 [17.0][FIX] account_financial_risk: Display the Financial Risk page correctly...
  account_financial_risk/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#442 [18.0][FIX] account_financial_risk: Display the Financial Risk page correct…
  account_financial_risk/views/res_partner_view.xml
Labels: approved, bot is merging ⏳
