Repository OCA/credit-control, pull requests merged in 2025-02, with the labels that each got.

#425 [ADD] [16.0] partner_risk_insurance_product_sticker_invoice_report
  partner_risk_insurance_product_sticker_invoice_report/README.rst
  partner_risk_insurance_product_sticker_invoice_report/__init__.py
  partner_risk_insurance_product_sticker_invoice_report/__manifest__.py
  partner_risk_insurance_product_sticker_invoice_report/i18n/es.po
  partner_risk_insurance_product_sticker_invoice_report/i18n/partner_risk_insurance_product_sticker_invoice_report.pot
  partner_risk_insurance_product_sticker_invoice_report/models/__init__.py
  partner_risk_insurance_product_sticker_invoice_report/models/account_move.py
  partner_risk_insurance_product_sticker_invoice_report/models/credit_policy_company.py
  partner_risk_insurance_product_sticker_invoice_report/models/product_sticker.py
  partner_risk_insurance_product_sticker_invoice_report/readme/CONFIGURE.md
  partner_risk_insurance_product_sticker_invoice_report/readme/CONTEXT.md
  partner_risk_insurance_product_sticker_invoice_report/readme/CONTRIBUTORS.md
  partner_risk_insurance_product_sticker_invoice_report/readme/DESCRIPTION.md
  partner_risk_insurance_product_sticker_invoice_report/readme/USAGE.md
  partner_risk_insurance_product_sticker_invoice_report/static/description/icon.png
  partner_risk_insurance_product_sticker_invoice_report/static/description/index.html
  partner_risk_insurance_product_sticker_invoice_report/tests/__init__.py
  partner_risk_insurance_product_sticker_invoice_report/tests/test_insurance_sticker.py
  partner_risk_insurance_product_sticker_invoice_report/views/credit_policy_company_view.xml
  partner_risk_insurance_product_sticker_invoice_report/views/product_sticker_view.xml
  setup/partner_risk_insurance_product_sticker_invoice_report/odoo/addons/partner_risk_insurance_product_sticker_invoice_report
  setup/partner_risk_insurance_product_sticker_invoice_report/setup.py
Labels: needs review, approved, merged 🎉

#429 [17.0][FIX] account_credit_control: Avoid error when opening or creating a mail template
  account_credit_control/models/credit_control_policy.py
  account_credit_control/views/credit_control_policy.xml
Labels: bot is merging ⏳

#428 [16.0][IMP] sale_payment_sheet_financial_risk: Discard payment sheets with paid invoices
  sale_payment_sheet_financial_risk/models/res_partner.py
Labels: approved, bot is merging ⏳

#431 [17.0][MIG] sale_financial_risk_info: Migration to 17.0
  sale_financial_risk_info/README.rst
  sale_financial_risk_info/__init__.py
  sale_financial_risk_info/__manifest__.py
  sale_financial_risk_info/i18n/es.po
  sale_financial_risk_info/i18n/it.po
  sale_financial_risk_info/i18n/sale_financial_risk_info.pot
  sale_financial_risk_info/models/__init__.py
  sale_financial_risk_info/models/res_partner.py
  sale_financial_risk_info/models/sale.py
  sale_financial_risk_info/pyproject.toml
  sale_financial_risk_info/readme/CONFIGURE.md
  sale_financial_risk_info/readme/CONTRIBUTORS.md
  sale_financial_risk_info/readme/DESCRIPTION.md
  sale_financial_risk_info/readme/USAGE.md
  sale_financial_risk_info/static/description/icon.png
  sale_financial_risk_info/static/description/index.html
  sale_financial_risk_info/tests/__init__.py
  sale_financial_risk_info/tests/test_sale_financial_risk_info.py
  sale_financial_risk_info/views/res_partner_view.xml
  sale_financial_risk_info/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#430 [17.0][IMP] account_credit_control: Send communication emails in background
  account_credit_control/README.rst
  account_credit_control/models/credit_control_communication.py
  account_credit_control/models/credit_control_run.py
  account_credit_control/tests/test_credit_control_run.py
Labels: approved, bot is merging ⏳

#433 [17.0][IMP] account_credit_control: Add Credit control subtype in partners to auto-subscribe in credit control lines
  account_credit_control/README.rst
  account_credit_control/data/data.xml
  account_credit_control/models/credit_control_line.py
  account_credit_control/readme/USAGE.md
  account_credit_control/static/description/index.html
  account_credit_control/tests/test_credit_control_run.py
Labels: approved, bot is merging ⏳

#432 [17.0][IMP] account_credit_control: Allow to create credit control lines with the maximum level for one control run
  account_credit_control/models/credit_control_line.py
  account_credit_control/models/credit_control_policy.py
  account_credit_control/models/res_config_settings.py
  account_credit_control/tests/test_credit_control_run.py
  account_credit_control/views/credit_control_line.xml
  account_credit_control/views/credit_control_policy.xml
  account_credit_control/views/res_config_settings_view.xml
  account_credit_control/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳

#435 [15.0][IMP] sale_financial_risk: New option to allow overrisk sale confirmation
  sale_financial_risk/models/__init__.py
  sale_financial_risk/models/res_company.py
  sale_financial_risk/models/res_config_settings.py
  sale_financial_risk/models/sale.py
  sale_financial_risk/views/res_config_settings.xml
Labels: approved, bot is merging ⏳
