Repository OCA/credit-control, pull requests merged in 2025-06, with the labels that each got.

#320 [16.0] account_invoice_overdue_reminder: change menu sequence
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard_view.xml
Labels: bot is merging ⏳, stale

#449 [18.0][FIX] sale_financial_risk: better format res_partner_view
  sale_financial_risk/views/res_partner_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#448 [18.0][FIX] account_financial_risk: better format res_partner_view
  account_financial_risk/views/res_partner_view.xml
Labels: needs review, approved, bot is merging ⏳
