Repository OCA/credit-control, pull requests merged in 2025-08, with the labels that each got.

#487 [16.0][IMP] account_financial_risk: Display credit information in portal view
  account_financial_risk/README.rst
  account_financial_risk/__manifest__.py
  account_financial_risk/i18n/account_financial_risk.pot
  account_financial_risk/i18n/es.po
  account_financial_risk/models/res_config.py
  account_financial_risk/models/res_partner.py
  account_financial_risk/readme/CONFIGURE.rst
  account_financial_risk/readme/DESCRIPTION.rst
  account_financial_risk/static/description/financial_risk_portal.png
  account_financial_risk/static/description/index.html
  account_financial_risk/views/portal_templates.xml
  account_financial_risk/views/res_config_view.xml
  account_financial_risk/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#467 [18.0][FIX] account_credit_control: correctly update control lines status
  account_credit_control/models/credit_control_communication.py
  account_credit_control/models/credit_control_run.py
  account_credit_control/models/mail_mail.py
  account_credit_control/tests/test_credit_control_run.py
  account_credit_control_queue_job/README.rst
  account_credit_control_queue_job/__init__.py
  account_credit_control_queue_job/__manifest__.py
  account_credit_control_queue_job/models/__init__.py
  account_credit_control_queue_job/models/credit_control_communication.py
  account_credit_control_queue_job/models/credit_control_run.py
  account_credit_control_queue_job/pyproject.toml
  account_credit_control_queue_job/readme/DESCRIPTION.md
  account_credit_control_queue_job/static/description/icon.png
  account_credit_control_queue_job/static/description/index.html
  account_credit_control_queue_job/tests/__init__.py
  account_credit_control_queue_job/tests/test_credit_control_run.py
  account_credit_control_queue_job/wizard/__init__.py
  account_credit_control_queue_job/wizard/res_config_settings.py
  account_credit_control_queue_job/wizard/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#489 [17.0] [IMP] account_financial_risk: Display credit information in portal view
  account_financial_risk/README.rst
  account_financial_risk/__manifest__.py
  account_financial_risk/models/res_config.py
  account_financial_risk/models/res_partner.py
  account_financial_risk/readme/CONFIGURE.md
  account_financial_risk/readme/DESCRIPTION.md
  account_financial_risk/static/description/financial_risk_portal.png
  account_financial_risk/static/description/index.html
  account_financial_risk/views/portal_templates.xml
  account_financial_risk/views/res_config_view.xml
  account_financial_risk/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#484 [16.0][IMP] account_invoice_overdue_reminder: optimize identification of unreconciled lines
  account_invoice_overdue_reminder/wizard/overdue_reminder_wizard.py
Labels: approved, ready to merge, bot is merging ⏳

#481 [18.0][FIX] account_financial_risk: Fix access rights on credit_limit
  account_financial_risk/models/account_invoice.py
  account_financial_risk/models/res_partner.py
  account_financial_risk/tests/test_account_financial_risk.py
  partner_risk_insurance/models/res_partner.py
  sale_financial_risk/models/sale.py
  sale_financial_risk_info/models/sale.py
Labels: approved, bot is merging ⏳

#496 [18.0][IMP] account_financial_risk: Add risk group to credit_limit field
  account_financial_risk/models/res_partner.py
Labels: bot is merging ⏳

#497 [15.0][IMP+FIX] account_credit_control: Defining the right data in the communication email
  account_credit_control/models/credit_control_communication.py
  account_credit_control/report/report_credit_control_summary.xml
  account_credit_control/views/credit_control_line.xml
Labels: approved, bot is merging ⏳
